-- ES INSTALL V14 core schema
-- Apply in Supabase SQL Editor or via migration tooling.

create table if not exists public.jobs (
  id text primary key,
  address text not null,
  builder text not null default '',
  community text not null default '',
  team text not null default '',
  date date not null,
  status text not null default 'Scheduled',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.installations (
  id bigint generated by default as identity primary key,
  job_id text not null references public.jobs(id) on delete cascade,
  team text not null default '',
  status text not null default 'Scheduled',
  scheduled_date date,
  scheduled_time text,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.warranties (
  id bigint generated by default as identity primary key,
  job_id text not null references public.jobs(id) on delete cascade,
  opened_at timestamptz not null default now(),
  issue text not null default '',
  status text not null default 'Open',
  priority text not null default 'Medium',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.evidence (
  id bigint generated by default as identity primary key,
  job_id text not null references public.jobs(id) on delete cascade,
  installation_id bigint references public.installations(id) on delete set null,
  warranty_id bigint references public.warranties(id) on delete set null,
  storage_path text not null,
  file_name text not null,
  mime_type text not null default 'application/octet-stream',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists installations_job_id_idx on public.installations(job_id);
create index if not exists warranties_job_id_idx on public.warranties(job_id);
create index if not exists evidence_job_id_idx on public.evidence(job_id);

alter table public.jobs enable row level security;
alter table public.installations enable row level security;
alter table public.warranties enable row level security;
alter table public.evidence enable row level security;

-- Authenticated users can access operational records.
-- Team-level authorization should be tightened with a profile/team table before production launch.
drop policy if exists "authenticated jobs" on public.jobs;
create policy "authenticated jobs" on public.jobs for all to authenticated using (true) with check (true);

drop policy if exists "authenticated installations" on public.installations;
create policy "authenticated installations" on public.installations for all to authenticated using (true) with check (true);

drop policy if exists "authenticated warranties" on public.warranties;
create policy "authenticated warranties" on public.warranties for all to authenticated using (true) with check (true);

drop policy if exists "authenticated evidence" on public.evidence;
create policy "authenticated evidence" on public.evidence for all to authenticated using (true) with check (true);

-- Storage bucket for installation/warranty evidence.
insert into storage.buckets (id, name, public)
values ('es-install-evidence', 'es-install-evidence', false)
on conflict (id) do nothing;

drop policy if exists "authenticated evidence read" on storage.objects;
create policy "authenticated evidence read" on storage.objects for select to authenticated using (bucket_id = 'es-install-evidence');

drop policy if exists "authenticated evidence upload" on storage.objects;
create policy "authenticated evidence upload" on storage.objects for insert to authenticated with check (bucket_id = 'es-install-evidence');

drop policy if exists "authenticated evidence update" on storage.objects;
create policy "authenticated evidence update" on storage.objects for update to authenticated using (bucket_id = 'es-install-evidence') with check (bucket_id = 'es-install-evidence');

drop policy if exists "authenticated evidence delete" on storage.objects;
create policy "authenticated evidence delete" on storage.objects for delete to authenticated using (bucket_id = 'es-install-evidence');
